export enum DrawActionTypes {
  RESET_STATE = 'RESET_STATE',

  // draw
  SET_DRAW_POINT_ACTIVE = 'SET_DRAW_POINT_ACTIVE',
  SET_DRAW_POLYLINE_ACTIVE = 'SET_DRAW_POLYLINE_ACTIVE',
  SET_DRAW_POLYGON_ACTIVE = 'SET_DRAW_POLYGON_ACTIVE',
}
