export enum Tool3DTileMutationTypes {
  RESET_STATE = 'RESET_STATE',

  // tool3dtile
  SET_HIGHLIGHT_3DTILE_FEATURE_ACTIVE = 'SET_HIGHLIGHT_3DTILE_FEATURE_ACTIVE',
  SET_HOVER_CLASSIFICATION_ACTIVE = 'SET_HOVER_CLASSIFICATION_ACTIVE',
  SET_CLICK_CLASSIFICATION_ACTIVE = 'SET_CLICK_CLASSIFICATION_ACTIVE',
}
