export enum MeasureMutationTypes {
  RESET_STATE = 'RESET_STATE',

  // measure
  SET_MEASURE_POINT_ACTIVE = 'SET_MEASURE_POINT_ACTIVE',
  SET_MEASURE_POLYLINE_ACTIVE = 'SET_MEASURE_POLYLINE_ACTIVE',
  SET_MEASURE_POLYGON_ACTIVE = 'SET_MEASURE_POLYGON_ACTIVE',
}
