export enum ToolbarActionTypes {
  RESET_STATE = 'RESET_STATE',

  SET_VISIBLE = 'SET_VISIBLE',
  SET_DROP_DOWN = 'SET_DROP_DOWN',

  // elevation contour
  SET_ELEVATION_CONTURE_ACTIVE = 'SET_ELEVATION_CONTURE_ACTIVE',

  // terrain sampling
  SET_TERRAIN_SAMPLING = 'SET_TERRAIN_SAMPLING',
}
