export enum SettingActionTypes {
  RESET_STATE = 'RESET_STATE',
  SET_SHOW_BROWSER_PANEL = 'SET_SHOW_BROWSER_PANEL',
  SET_SHOW_TOOLBAR = 'SET_SHOW_TOOLBAR',
  SET_SHOW_SETTING = 'SET_SHOW_SETTING',
}
