export enum LocationBarActionTypes {
  RESET_STATE = 'RESET_STATE',
  SET_SHOW_CAMERA_LOCATION = 'SET_SHOW_CAMERA_LOCATION',
  SET_SHOW_MOUSE_LOCATION = 'SET_SHOW_MOUSE_LOCATION',
  SET_SHOW_FPS = 'SET_SHOW_FPS',
}
